// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tekever_Challenge.Data;

#nullable disable

namespace Tekever_Challenge.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251016170651_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cillian Murphy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bryan Cranston"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jennifer Aniston"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pedro Pascal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Millie Bobby Brown"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Henry Cavill"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Emma D'Arcy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tom Hiddleston"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Anya Taylor-Joy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Matthew McConaughey"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Zendaya"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Rami Malek"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Elizabeth Olsen"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kit Harington"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Oscar Isaac"
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedtAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TvShowId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReleaseDate = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 1
                        },
                        new
                        {
                            Id = 2,
                            ReleaseDate = new DateTime(2014, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 2,
                            TvShowId = 1
                        },
                        new
                        {
                            Id = 3,
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 2
                        },
                        new
                        {
                            Id = 4,
                            ReleaseDate = new DateTime(2009, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 2,
                            TvShowId = 2
                        },
                        new
                        {
                            Id = 5,
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 3
                        },
                        new
                        {
                            Id = 6,
                            ReleaseDate = new DateTime(1995, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 2,
                            TvShowId = 3
                        },
                        new
                        {
                            Id = 7,
                            ReleaseDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 4
                        },
                        new
                        {
                            Id = 8,
                            ReleaseDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 5
                        },
                        new
                        {
                            Id = 9,
                            ReleaseDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 2,
                            TvShowId = 5
                        },
                        new
                        {
                            Id = 10,
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 6
                        },
                        new
                        {
                            Id = 11,
                            ReleaseDate = new DateTime(2012, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 2,
                            TvShowId = 6
                        },
                        new
                        {
                            Id = 12,
                            ReleaseDate = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 7
                        },
                        new
                        {
                            Id = 13,
                            ReleaseDate = new DateTime(2017, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 2,
                            TvShowId = 7
                        },
                        new
                        {
                            Id = 14,
                            ReleaseDate = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 8
                        },
                        new
                        {
                            Id = 15,
                            ReleaseDate = new DateTime(2020, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 9
                        },
                        new
                        {
                            Id = 16,
                            ReleaseDate = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 10
                        },
                        new
                        {
                            Id = 17,
                            ReleaseDate = new DateTime(2015, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 11
                        },
                        new
                        {
                            Id = 18,
                            ReleaseDate = new DateTime(2019, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 12
                        },
                        new
                        {
                            Id = 19,
                            ReleaseDate = new DateTime(2019, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 13
                        },
                        new
                        {
                            Id = 20,
                            ReleaseDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 14
                        },
                        new
                        {
                            Id = 21,
                            ReleaseDate = new DateTime(2014, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 15
                        },
                        new
                        {
                            Id = 22,
                            ReleaseDate = new DateTime(2015, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 16
                        },
                        new
                        {
                            Id = 23,
                            ReleaseDate = new DateTime(2015, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 17
                        },
                        new
                        {
                            Id = 24,
                            ReleaseDate = new DateTime(2015, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 18
                        },
                        new
                        {
                            Id = 25,
                            ReleaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 19
                        },
                        new
                        {
                            Id = 26,
                            ReleaseDate = new DateTime(2010, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 1,
                            TvShowId = 20
                        },
                        new
                        {
                            Id = 27,
                            ReleaseDate = new DateTime(2011, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 2,
                            TvShowId = 20
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.SeasonEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AirDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("double");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonEpisodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirDate = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.5999999999999996,
                            SeasonId = 1,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 2,
                            AirDate = new DateTime(2013, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.6999999999999993,
                            SeasonId = 1,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 3,
                            AirDate = new DateTime(2014, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.9000000000000004,
                            SeasonId = 2,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 4,
                            AirDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 9.0,
                            SeasonId = 3,
                            Title = "Pilot"
                        },
                        new
                        {
                            Id = 5,
                            AirDate = new DateTime(2008, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.6999999999999993,
                            SeasonId = 3,
                            Title = "Cat's in the Bag..."
                        },
                        new
                        {
                            Id = 6,
                            AirDate = new DateTime(2009, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 9.0999999999999996,
                            SeasonId = 4,
                            Title = "Season 2 Premiere"
                        },
                        new
                        {
                            Id = 7,
                            AirDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.3000000000000007,
                            SeasonId = 5,
                            Title = "The One Where It All Began"
                        },
                        new
                        {
                            Id = 8,
                            AirDate = new DateTime(1994, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.4000000000000004,
                            SeasonId = 5,
                            Title = "The One with the Sonogram"
                        },
                        new
                        {
                            Id = 9,
                            AirDate = new DateTime(1995, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.5,
                            SeasonId = 6,
                            Title = "Season 2 Premiere"
                        },
                        new
                        {
                            Id = 10,
                            AirDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.9000000000000004,
                            SeasonId = 7,
                            Title = "Chapter 1: The Mandalorian"
                        },
                        new
                        {
                            Id = 11,
                            AirDate = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.8000000000000007,
                            SeasonId = 7,
                            Title = "Chapter 2: The Child"
                        },
                        new
                        {
                            Id = 12,
                            AirDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.1999999999999993,
                            SeasonId = 8,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 13,
                            AirDate = new DateTime(2019, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.4000000000000004,
                            SeasonId = 8,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 14,
                            AirDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.5,
                            SeasonId = 9,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 15,
                            AirDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 9.0,
                            SeasonId = 10,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 16,
                            AirDate = new DateTime(2011, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.9000000000000004,
                            SeasonId = 10,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 17,
                            AirDate = new DateTime(2012, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 9.0999999999999996,
                            SeasonId = 11,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 18,
                            AirDate = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.4000000000000004,
                            SeasonId = 12,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 19,
                            AirDate = new DateTime(2021, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.5999999999999996,
                            SeasonId = 12,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 20,
                            AirDate = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 3,
                            Rating = 8.5,
                            SeasonId = 12,
                            Title = "Episode 3"
                        },
                        new
                        {
                            Id = 21,
                            AirDate = new DateTime(2020, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 7.7999999999999998,
                            SeasonId = 13,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 22,
                            AirDate = new DateTime(2020, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 7.9000000000000004,
                            SeasonId = 13,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 23,
                            AirDate = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.0,
                            SeasonId = 14,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 24,
                            AirDate = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.1999999999999993,
                            SeasonId = 14,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 25,
                            AirDate = new DateTime(2022, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 3,
                            Rating = 8.0999999999999996,
                            SeasonId = 14,
                            Title = "Episode 3"
                        },
                        new
                        {
                            Id = 26,
                            AirDate = new DateTime(2015, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.3000000000000007,
                            SeasonId = 15,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 27,
                            AirDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.1999999999999993,
                            SeasonId = 15,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 28,
                            AirDate = new DateTime(2019, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.5,
                            SeasonId = 16,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 29,
                            AirDate = new DateTime(2019, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.5999999999999996,
                            SeasonId = 16,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 30,
                            AirDate = new DateTime(2019, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 7.9000000000000004,
                            SeasonId = 17,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 31,
                            AirDate = new DateTime(2019, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.0,
                            SeasonId = 17,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 32,
                            AirDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.0999999999999996,
                            SeasonId = 18,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 33,
                            AirDate = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.1999999999999993,
                            SeasonId = 18,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 34,
                            AirDate = new DateTime(2014, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.0,
                            SeasonId = 19,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 35,
                            AirDate = new DateTime(2014, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 8.0999999999999996,
                            SeasonId = 19,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 36,
                            AirDate = new DateTime(2015, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 7.9000000000000004,
                            SeasonId = 20,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 37,
                            AirDate = new DateTime(2015, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.3000000000000007,
                            SeasonId = 21,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 38,
                            AirDate = new DateTime(2015, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.1999999999999993,
                            SeasonId = 22,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 39,
                            AirDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.4000000000000004,
                            SeasonId = 23,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 40,
                            AirDate = new DateTime(2010, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 7.7999999999999998,
                            SeasonId = 24,
                            Title = "Episode 1"
                        },
                        new
                        {
                            Id = 41,
                            AirDate = new DateTime(2010, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 2,
                            Rating = 7.9000000000000004,
                            SeasonId = 24,
                            Title = "Episode 2"
                        },
                        new
                        {
                            Id = 42,
                            AirDate = new DateTime(2011, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            Rating = 8.0,
                            SeasonId = 25,
                            Title = "Episode 1"
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<double?>("Rating")
                        .HasColumnType("double");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TvShows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "British crime drama",
                            Rating = 9.0999999999999996,
                            ReleaseDate = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Peaky Blinders"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chemistry teacher turns to crime",
                            Rating = 9.5,
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breaking Bad"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Six friends navigate life in NYC",
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Friends"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Star Wars bounty hunter saga",
                            Rating = 8.6999999999999993,
                            ReleaseDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Mandalorian"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A monster hunter struggles with his destiny",
                            Rating = 8.1999999999999993,
                            ReleaseDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Noble families vie for control of Westeros",
                            Rating = 9.3000000000000007,
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game of Thrones"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A group of kids uncover supernatural mysteries",
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stranger Things"
                        },
                        new
                        {
                            Id = 8,
                            Description = "God of Mischief faces the TVA",
                            Rating = 8.4000000000000004,
                            ReleaseDate = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Loki"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Chess prodigy battles addiction and rivals",
                            Rating = 8.5999999999999996,
                            ReleaseDate = new DateTime(2020, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Queen’s Gambit"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Targaryen civil war begins",
                            Rating = 8.8000000000000007,
                            ReleaseDate = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "House of the Dragon"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Hacker tries to take down corporate America",
                            Rating = 8.5999999999999996,
                            ReleaseDate = new DateTime(2015, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mr. Robot"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Teens navigate love and addiction",
                            Rating = 8.4000000000000004,
                            ReleaseDate = new DateTime(2019, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Euphoria"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A group of vigilantes fight corrupt superheroes",
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(2019, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Boys"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Superhero sitcom blending reality and fantasy",
                            Rating = 8.0,
                            ReleaseDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "WandaVision"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Detectives uncover dark truths",
                            Rating = 9.0,
                            ReleaseDate = new DateTime(2014, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "True Detective"
                        },
                        new
                        {
                            Id = 16,
                            Description = "A lawyer's descent into moral ambiguity",
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(2015, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Better Call Saul"
                        },
                        new
                        {
                            Id = 17,
                            Description = "The story of Pablo Escobar and the DEA",
                            Rating = 8.8000000000000007,
                            ReleaseDate = new DateTime(2015, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Narcos"
                        },
                        new
                        {
                            Id = 18,
                            Description = "A sci-fi political thriller set in space",
                            Rating = 8.5,
                            ReleaseDate = new DateTime(2015, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Expanse"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Survivors navigate a post-apocalyptic world",
                            Rating = 9.1999999999999993,
                            ReleaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Modern adaptation of Sherlock Holmes",
                            Rating = 9.0999999999999996,
                            ReleaseDate = new DateTime(2010, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sherlock"
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShowActor", b =>
                {
                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("TvShowId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("TvShowActors");

                    b.HasData(
                        new
                        {
                            TvShowId = 1,
                            ActorId = 1
                        },
                        new
                        {
                            TvShowId = 1,
                            ActorId = 14
                        },
                        new
                        {
                            TvShowId = 2,
                            ActorId = 2
                        },
                        new
                        {
                            TvShowId = 2,
                            ActorId = 12
                        },
                        new
                        {
                            TvShowId = 3,
                            ActorId = 3
                        },
                        new
                        {
                            TvShowId = 3,
                            ActorId = 13
                        },
                        new
                        {
                            TvShowId = 4,
                            ActorId = 4
                        },
                        new
                        {
                            TvShowId = 4,
                            ActorId = 8
                        },
                        new
                        {
                            TvShowId = 5,
                            ActorId = 6
                        },
                        new
                        {
                            TvShowId = 5,
                            ActorId = 9
                        },
                        new
                        {
                            TvShowId = 6,
                            ActorId = 14
                        },
                        new
                        {
                            TvShowId = 6,
                            ActorId = 6
                        },
                        new
                        {
                            TvShowId = 7,
                            ActorId = 5
                        },
                        new
                        {
                            TvShowId = 7,
                            ActorId = 11
                        },
                        new
                        {
                            TvShowId = 8,
                            ActorId = 8
                        },
                        new
                        {
                            TvShowId = 8,
                            ActorId = 15
                        },
                        new
                        {
                            TvShowId = 9,
                            ActorId = 9
                        },
                        new
                        {
                            TvShowId = 9,
                            ActorId = 10
                        },
                        new
                        {
                            TvShowId = 10,
                            ActorId = 7
                        },
                        new
                        {
                            TvShowId = 10,
                            ActorId = 14
                        },
                        new
                        {
                            TvShowId = 11,
                            ActorId = 12
                        },
                        new
                        {
                            TvShowId = 12,
                            ActorId = 11
                        },
                        new
                        {
                            TvShowId = 12,
                            ActorId = 3
                        },
                        new
                        {
                            TvShowId = 13,
                            ActorId = 15
                        },
                        new
                        {
                            TvShowId = 13,
                            ActorId = 2
                        },
                        new
                        {
                            TvShowId = 14,
                            ActorId = 13
                        },
                        new
                        {
                            TvShowId = 15,
                            ActorId = 10
                        },
                        new
                        {
                            TvShowId = 16,
                            ActorId = 2
                        },
                        new
                        {
                            TvShowId = 17,
                            ActorId = 15
                        },
                        new
                        {
                            TvShowId = 18,
                            ActorId = 15
                        },
                        new
                        {
                            TvShowId = 19,
                            ActorId = 4
                        },
                        new
                        {
                            TvShowId = 19,
                            ActorId = 5
                        },
                        new
                        {
                            TvShowId = 20,
                            ActorId = 10
                        },
                        new
                        {
                            TvShowId = 20,
                            ActorId = 1
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShowGenre", b =>
                {
                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("TvShowId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TvShowGenres");

                    b.HasData(
                        new
                        {
                            TvShowId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 1,
                            GenreId = 7
                        },
                        new
                        {
                            TvShowId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            TvShowId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 2,
                            GenreId = 7
                        },
                        new
                        {
                            TvShowId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            TvShowId = 3,
                            GenreId = 8
                        },
                        new
                        {
                            TvShowId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            TvShowId = 4,
                            GenreId = 8
                        },
                        new
                        {
                            TvShowId = 5,
                            GenreId = 6
                        },
                        new
                        {
                            TvShowId = 5,
                            GenreId = 3
                        },
                        new
                        {
                            TvShowId = 6,
                            GenreId = 6
                        },
                        new
                        {
                            TvShowId = 6,
                            GenreId = 5
                        },
                        new
                        {
                            TvShowId = 7,
                            GenreId = 4
                        },
                        new
                        {
                            TvShowId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 8,
                            GenreId = 4
                        },
                        new
                        {
                            TvShowId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            TvShowId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 9,
                            GenreId = 5
                        },
                        new
                        {
                            TvShowId = 10,
                            GenreId = 6
                        },
                        new
                        {
                            TvShowId = 10,
                            GenreId = 5
                        },
                        new
                        {
                            TvShowId = 11,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 11,
                            GenreId = 5
                        },
                        new
                        {
                            TvShowId = 12,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 13,
                            GenreId = 3
                        },
                        new
                        {
                            TvShowId = 13,
                            GenreId = 5
                        },
                        new
                        {
                            TvShowId = 14,
                            GenreId = 4
                        },
                        new
                        {
                            TvShowId = 14,
                            GenreId = 2
                        },
                        new
                        {
                            TvShowId = 15,
                            GenreId = 7
                        },
                        new
                        {
                            TvShowId = 15,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 16,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 16,
                            GenreId = 7
                        },
                        new
                        {
                            TvShowId = 17,
                            GenreId = 7
                        },
                        new
                        {
                            TvShowId = 17,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 18,
                            GenreId = 4
                        },
                        new
                        {
                            TvShowId = 18,
                            GenreId = 8
                        },
                        new
                        {
                            TvShowId = 19,
                            GenreId = 1
                        },
                        new
                        {
                            TvShowId = 19,
                            GenreId = 8
                        },
                        new
                        {
                            TvShowId = 20,
                            GenreId = 7
                        },
                        new
                        {
                            TvShowId = 20,
                            GenreId = 5
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Tekever_Challenge.Models.UserFavorites", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TvShowId");

                    b.HasIndex("TvShowId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tekever_Challenge.Models.RefreshToken", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.User", "UserToken")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserToken");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Season", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.TvShow", "TvShow")
                        .WithMany("Seasons")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.SeasonEpisode", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShowActor", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.Actor", "Actor")
                        .WithMany("TvShowActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekever_Challenge.Models.TvShow", "TvShow")
                        .WithMany("TvShowActors")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShowGenre", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.Genre", "Genre")
                        .WithMany("TvShowGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekever_Challenge.Models.TvShow", "TvShow")
                        .WithMany("TvShowGenres")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.UserFavorites", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.TvShow", "TvShow")
                        .WithMany("UserFavorites")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Actor", b =>
                {
                    b.Navigation("TvShowActors");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Genre", b =>
                {
                    b.Navigation("TvShowGenres");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShow", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("TvShowActors");

                    b.Navigation("TvShowGenres");

                    b.Navigation("UserFavorites");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
