// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tekever_Challenge.Data;

#nullable disable

namespace Tekever_Challenge.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251010231241_populate")]
    partial class populate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Carter"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Emma Wilson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Carlos Vega"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mia Chen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tom Novak"
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TvShowId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 30001,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2022, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Peaky Blinders - Episode 1",
                            TvShowId = 2001
                        },
                        new
                        {
                            Id = 30002,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2022, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Peaky Blinders - Episode 2",
                            TvShowId = 2001
                        },
                        new
                        {
                            Id = 30003,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2022, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Peaky Blinders - Episode 3",
                            TvShowId = 2001
                        },
                        new
                        {
                            Id = 30004,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2022, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Peaky Blinders - Episode 4",
                            TvShowId = 2001
                        },
                        new
                        {
                            Id = 30005,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Peaky Blinders - Episode 5",
                            TvShowId = 2001
                        },
                        new
                        {
                            Id = 30006,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2023, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Suits - Episode 1",
                            TvShowId = 2002
                        },
                        new
                        {
                            Id = 30007,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Suits - Episode 2",
                            TvShowId = 2002
                        },
                        new
                        {
                            Id = 30008,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2023, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Suits - Episode 3",
                            TvShowId = 2002
                        },
                        new
                        {
                            Id = 30009,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Suits - Episode 4",
                            TvShowId = 2002
                        },
                        new
                        {
                            Id = 30010,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2021, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Friends - Episode 1",
                            TvShowId = 2003
                        },
                        new
                        {
                            Id = 30011,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Friends - Episode 2",
                            TvShowId = 2003
                        },
                        new
                        {
                            Id = 30012,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2021, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Friends - Episode 3",
                            TvShowId = 2003
                        },
                        new
                        {
                            Id = 30013,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2021, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Friends - Episode 4",
                            TvShowId = 2003
                        },
                        new
                        {
                            Id = 30014,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2021, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Friends - Episode 5",
                            TvShowId = 2003
                        },
                        new
                        {
                            Id = 30015,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Modern Family - Episode 1",
                            TvShowId = 2004
                        },
                        new
                        {
                            Id = 30016,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2021, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Modern Family - Episode 2",
                            TvShowId = 2004
                        },
                        new
                        {
                            Id = 30017,
                            EpisodeNumber = 0,
                            ReleaseDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonNumber = 0,
                            Title = "Modern Family - Episode 3",
                            TvShowId = 2004
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedtAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<double?>("Rating")
                        .HasColumnType("double");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TvShows");

                    b.HasData(
                        new
                        {
                            Id = 2001,
                            Rating = 9.0,
                            ReleaseDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Peaky Blinders"
                        },
                        new
                        {
                            Id = 2002,
                            Rating = 8.8000000000000007,
                            ReleaseDate = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Suits"
                        },
                        new
                        {
                            Id = 2003,
                            Rating = 5.2000000000000002,
                            ReleaseDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Friends"
                        },
                        new
                        {
                            Id = 2004,
                            Rating = 9.5,
                            ReleaseDate = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Modern Family"
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShowActor", b =>
                {
                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("TvShowId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("TvShowActors");

                    b.HasData(
                        new
                        {
                            TvShowId = 2001,
                            ActorId = 5
                        },
                        new
                        {
                            TvShowId = 2001,
                            ActorId = 1
                        },
                        new
                        {
                            TvShowId = 2002,
                            ActorId = 5
                        },
                        new
                        {
                            TvShowId = 2002,
                            ActorId = 1
                        },
                        new
                        {
                            TvShowId = 2003,
                            ActorId = 2
                        },
                        new
                        {
                            TvShowId = 2003,
                            ActorId = 1
                        },
                        new
                        {
                            TvShowId = 2003,
                            ActorId = 5
                        },
                        new
                        {
                            TvShowId = 2004,
                            ActorId = 2
                        },
                        new
                        {
                            TvShowId = 2004,
                            ActorId = 5
                        },
                        new
                        {
                            TvShowId = 2004,
                            ActorId = 3
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShowGenre", b =>
                {
                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("TvShowId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TvShowGenres");

                    b.HasData(
                        new
                        {
                            TvShowId = 2001,
                            GenreId = 105
                        },
                        new
                        {
                            TvShowId = 2002,
                            GenreId = 103
                        },
                        new
                        {
                            TvShowId = 2003,
                            GenreId = 105
                        },
                        new
                        {
                            TvShowId = 2004,
                            GenreId = 103
                        },
                        new
                        {
                            TvShowId = 2004,
                            GenreId = 105
                        });
                });

            modelBuilder.Entity("Tekever_Challenge.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Tekever_Challenge.Models.UserFavorites", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TvShowId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TvShowId");

                    b.HasIndex("TvShowId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Episode", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.TvShow", null)
                        .WithMany("Episodes")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tekever_Challenge.Models.RefreshToken", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.User", "UserToken")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserToken");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShowActor", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.Actor", null)
                        .WithMany("TvShowActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekever_Challenge.Models.TvShow", null)
                        .WithMany("TvShowActors")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShowGenre", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.Genre", null)
                        .WithMany("TvShowGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekever_Challenge.Models.TvShow", null)
                        .WithMany("TvShowGenres")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tekever_Challenge.Models.UserFavorites", b =>
                {
                    b.HasOne("Tekever_Challenge.Models.TvShow", null)
                        .WithMany("UserFavorites")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tekever_Challenge.Models.User", null)
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Actor", b =>
                {
                    b.Navigation("TvShowActors");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.Genre", b =>
                {
                    b.Navigation("TvShowGenres");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.TvShow", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("TvShowActors");

                    b.Navigation("TvShowGenres");

                    b.Navigation("UserFavorites");
                });

            modelBuilder.Entity("Tekever_Challenge.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
